# Cloudflare Pages configuration for frontend static deployment
name = "cloudflare-static-deployer"
compatibility_date = "2024-01-01"

# Production environment for Pages
[env.production]
name = "cloudflare-static-deployer"

# Staging environment for Pages
[env.staging]
name = "cloudflare-static-deployer-staging"

# Pages-specific configuration (no Workers needed)
[build]
command = "npm run build:prod"
cwd = "."
watch_dir = "src"

# Static site environment variables
[vars]
ENVIRONMENT = "production"
DEPLOYMENT_TYPE = "static"

# Pages deployment settings
[pages]
build_output_dir = "dist"
build_command = "npm run build:prod"
# No functions directory - pure static deployment