# Cloudflare Pages configuration
[build]
command = "npm run build:frontend"
publish = "frontend/dist"

[build.environment_variables]
NODE_ENV = "production"
VITE_API_BASE_URL = "https://api.cloudflare-deployer.com"

# Development preview settings
[preview]
command = "npm run build:frontend"
publish = "frontend/dist"

[preview.environment_variables]
NODE_ENV = "development"
VITE_API_BASE_URL = "https://api-dev.cloudflare-deployer.com"

# Custom domains and routing
[deployment]
compatibility_date = "2024-01-01"
compatibility_flags = []

# Build settings
[build.processing]
css = true
js = true
html = true
images = true

# Security settings
[security]
always_use_https = true
automatic_https_rewrites = true