name = "cloudflare-static-deployer"
compatibility_date = "2024-01-01"

# Pages configuration
[env.production]
compatibility_date = "2024-01-01"

# Build configuration for Pages
[build]
command = "npm run build:frontend"
cwd = "."
watch_dir = "frontend"

[build.environment_variables]
NODE_ENV = "production"
VITE_API_BASE_URL = "https://api.cloudflare-deployer.com"

# Development environment
[env.development]
compatibility_date = "2024-01-01"

[env.development.build]
command = "npm run build:frontend"
watch_dir = "frontend"

[env.development.build.environment_variables]
NODE_ENV = "development"
VITE_API_BASE_URL = "http://localhost:3000"

# Staging environment
[env.staging]
compatibility_date = "2024-01-01"

[env.staging.build]
command = "npm run build:frontend"
watch_dir = "frontend"

[env.staging.build.environment_variables]
NODE_ENV = "staging"
VITE_API_BASE_URL = "https://api-staging.cloudflare-deployer.com"