# Cloudflare Workers Configuration for Backend API
name = "cloudflare-static-deployer-api"
main = "worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Worker configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = ["worker.ts", "src/"]

# Environment Variables (will be loaded from .env file in development)
[vars]
NODE_ENV = "production"
CORS_ORIGINS = "https://luckyjingwen.top,https://www.luckyjingwen.top,https://cloudflare-static-deployer.pages.dev"
API_VERSION = "v1"
LOG_LEVEL = "info"

# Security Configuration
ENABLE_SECURITY_HEADERS = "true"
ENABLE_CSP = "true"
ENABLE_RATE_LIMITING = "true"
RATE_LIMIT_MAX = "1000"
RATE_LIMIT_WINDOW = "900000"
MAX_FILE_SIZE = "10485760"
ALLOWED_FILE_TYPES = "application/zip,application/x-zip-compressed"

# Development Environment Variables (loaded from .env file)
[env.development.vars]
NODE_ENV = "development"
LOG_LEVEL = "debug"

# Development server configuration
[dev]
port = 3000

# Routes configuration
[[routes]]
pattern = "api.luckyjingwen.top/*"
zone_name = "luckyjingwen.top"

# Worker limits and configuration
# [limits]
# cpu_ms = 50  # CPU limits not supported on Free plan

# Placement configuration for optimal performance
[placement]
mode = "smart"

# Observability configuration
[observability]
enabled = true